[edr] [LINUXDAR-3264] address PR comments. Use SOPHOS_INSTALL env variable for shared_pipe paths in installer. Use common teardown in new robot suite

diff --git a/edr/products/installer/install.sh.in b/edr/products/installer/install.sh.in
--- a/edr/products/installer/install.sh.in
+++ b/edr/products/installer/install.sh.in
@@ -249,7 +249,7 @@ function is_rsyslog_running()
 
 function enable_access_for_rsyslog_to_shared_pipe()
 {
-    semanage fcontext -a -t var_log_t /opt/sophos-spl/shared/syslog_pipe && restorecon -Fv /opt/sophos-spl/shared/syslog_pipe
+    semanage fcontext -a -t var_log_t ${SOPHOS_INSTALL}/shared/syslog_pipe && restorecon -Fv ${SOPHOS_INSTALL}/shared/syslog_pipe
 }
 
 # Check key files have been installed
@@ -286,9 +286,9 @@ then
       then
         if which semanage > /dev/null
         then
-          enable_access_for_rsyslog_to_shared_pipe || echo "WARNING: Failed to add var_log_t context to /opt/sophos-spl/shared/syslog_pipe"
+          enable_access_for_rsyslog_to_shared_pipe || echo "WARNING: Failed to add var_log_t context to ${SOPHOS_INSTALL}/shared/syslog_pipe"
         else
-          echo "WARNING: Detected selinux is present on system, but could not find semanage executable to add var_log_t context to /opt/sophos-spl/shared/syslog_pipe"
+          echo "WARNING: Detected selinux is present on system, but could not find semanage executable to add var_log_t context to ${SOPHOS_INSTALL}/shared/syslog_pipe"
         fi
       fi
       systemctl restart rsyslog
