[av] [LINUXDAR-5417] Do not register On-access as a plugin or start the process

diff --git a/av/products/installer/install.sh.in b/av/products/installer/install.sh.in
--- a/av/products/installer/install.sh.in
+++ b/av/products/installer/install.sh.in
@@ -87,7 +87,6 @@ SUSI_UPDATE_SRC="$SOPHOS_INSTALL/plugins/av/chroot/susi/update_source/"
 SUSI_DIST_VERS="$SOPHOS_INSTALL/plugins/av/chroot/susi/distribution_version/"
 SUSI_V1DIR="${SUSI_DIST_VERS}version1/"
 LOCKFILE="${PLUGIN_INSTALL}/chroot/var/susi_update.lock"
-TD_PID_FILE="${PLUGIN_INSTALL}/chroot/var/threat_detector.pid"
 
 function delete_removed_vdl()
 {
@@ -241,11 +240,6 @@ function apply_permissions()
     chown -R ${USER_NAME}:${GROUP_NAME} "${PLUGIN_INSTALL}/var"
     chown root:${GROUP_NAME} "${PLUGIN_INSTALL}/var"
 
-    local safestore_var="${PLUGIN_INSTALL}/var/safestore_db"
-    mkdir -p "$safestore_var"
-    chmod 0700 "${safestore_var}"
-    chown root:root "${safestore_var}"
-
     CHROOT="${PLUGIN_INSTALL}/chroot"
     CHROOT_LINK_DIR="${CHROOT}/${PLUGIN_INSTALL#/}"
     mkdir -p ${CHROOT_LINK_DIR}
@@ -304,23 +298,9 @@ function apply_permissions()
     chown root:${GROUP_NAME} "${CHROOT}/var"
     touch ${LOCKFILE}
     chown ${THREAT_DETECTOR_USER}:${GROUP_NAME} ${LOCKFILE}
-    if [[ -f ${TD_PID_FILE} ]]
-    then
-        chown ${THREAT_DETECTOR_USER}:${GROUP_NAME} ${TD_PID_FILE}
-        chmod 644 ${TD_PID_FILE}
-    fi
 
     chmod 0711 ${CHROOT}
     chown root:${GROUP_NAME} "${CHROOT}"
-}
-
-function create_registration_file()
-{
-  local NAME=$1
-  local TEMP_REG_FILE=${SOPHOS_INSTALL}/tmp/${NAME}.json
-  sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/${NAME}.json" > "${TEMP_REG_FILE}"
-  "${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_REG_FILE}"
-  rm -f ${TEMP_REG_FILE}
 }
 
 function install_product()
@@ -349,11 +329,19 @@ function install_product()
         timeout 10 tail --pid=$(pgrep -G ${GROUP_NAME} sophos_threat_d) -f /dev/null 2> /dev/null
     fi
 
-    #Create plugin registration files
-    create_registration_file ${PLUGIN_NAME}
-    create_registration_file "threat_detector"
-    create_registration_file "on_access_process"
-    create_registration_file "safestore"
+    #Create plugin registration file
+    local TEMP_PLUGIN_REG_FILE=${SOPHOS_INSTALL}/tmp/${PLUGIN_NAME}.json
+    local TEMP_THREAT_DETECTOR_REG_FILE=${SOPHOS_INSTALL}/tmp/threat_detector.json
+    #local TEMP_ONACCESS_PROCESS_REG_FILE=${SOPHOS_INSTALL}/tmp/on_access_process.json
+    sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/${PLUGIN_NAME}.json"  > "${TEMP_PLUGIN_REG_FILE}"
+    sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/threat_detector.json" > "${TEMP_THREAT_DETECTOR_REG_FILE}"
+    #sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/on_access_process.json" > "${TEMP_ONACCESS_PROCESS_REG_FILE}"
+    "${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_PLUGIN_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_PLUGIN_REG_FILE}"
+    "${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_THREAT_DETECTOR_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_THREAT_DETECTOR_REG_FILE}"
+    #"${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_ONACCESS_PROCESS_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_ONACCESS_PROCESS_REG_FILE}"
+    rm -f ${TEMP_PLUGIN_REG_FILE}
+    rm -f ${TEMP_THREAT_DETECTOR_REG_FILE}
+    #rm -f ${TEMP_ONACCESS_PROCESS_REG_FILE}
 
     #Install files using versioned copy (apart from SUSI)
     find "$DIST/files/plugins" -type f -not -path "$DIST/files/plugins/av/chroot/susi/*" -print0 \
@@ -398,16 +386,17 @@ function install_product()
 
     ln -snf "${PLUGIN_INSTALL}/bin/avscanner" /usr/local/bin/avscanner
 
+    delete_removed_vdl
     generate_susi_package_manifest
     bootstrap_susi_from_update_source
 
     #After install start AV Plugin
     "${SOPHOS_INSTALL}/bin/wdctl" start "${PLUGIN_NAME}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start plugin ${PLUGIN_NAME}"
 
-    #Then start relevant processes
+    #Then start sophos_threat_detector
     "${SOPHOS_INSTALL}/bin/wdctl" start threat_detector || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start sophos_threat_detector"
-    "${SOPHOS_INSTALL}/bin/wdctl" start on_access_process || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start sophos on-access process"
-    "${SOPHOS_INSTALL}/bin/wdctl" start safestore || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start SafeStore"
+
+    #"${SOPHOS_INSTALL}/bin/wdctl" start on_access_process || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start sophos on-access process"
 
     cp "$DIST/manifest.dat" "${VAR}/manifest.dat" || failure ${EXIT_FAIL_COPY_MANIFEST} "Failed to copy manifest from install-set to installation"
 }
@@ -423,15 +412,12 @@ function update_supplement()
     else
         echo "Lock acquired on $LOCKFILE"
         UPDATE_SRC="plugins/av/chroot/susi/update_source"
-
-        $SOPHOS_INSTALL/plugins/av/sbin/sync_versioned_files "$DIST/files/$UPDATE_SRC/vdl" "$SOPHOS_INSTALL/$UPDATE_SRC/vdl" --copy \
-            || failure ${EXIT_FAIL_NONVERSIONEDCOPY} "Failed to copy Virus Data to installation"
-
+        cp -auv "$DIST/files/$UPDATE_SRC/vdl/"* "$SOPHOS_INSTALL/$UPDATE_SRC/vdl/" || failure ${EXIT_FAIL_NONVERSIONEDCOPY} "Failed to copy Virus Data to installation"
         cp -auv "$DIST/files/$UPDATE_SRC/model/"* "$SOPHOS_INSTALL/$UPDATE_SRC/model/" || failure ${EXIT_FAIL_NONVERSIONEDCOPY} "Failed to copy ML Model to installation"
         cp -auv "$DIST/files/$UPDATE_SRC/reputation/"* "$SOPHOS_INSTALL/$UPDATE_SRC/reputation/" || failure ${EXIT_FAIL_NONVERSIONEDCOPY} "Failed to copy Local reputation data to installation"
         cp -auv "$DIST/files/$UPDATE_SRC/rules/"* "$SOPHOS_INSTALL/$UPDATE_SRC/rules/" || failure ${EXIT_FAIL_NONVERSIONEDCOPY} "Failed to copy LUA files to installation"
         set_permissions_on_susi_update_source
-
+        delete_removed_vdl
     fi
 
     generate_susi_package_manifest
