[av] [LINUXDAR-1788] Alter install script to assume supplement update only if manifest file hasn't changed.
Use faster versionedcopy interface.
Use functions.
Add no-arg version of createInstallSet.py - assumes /opt/test/inputs/av/INSTALL-SET /opt/test/inputs/av/SDDS-COMPONENT /opt/test/inputs as args.

diff --git a/av/products/installer/install.sh.in b/av/products/installer/install.sh.in
--- a/av/products/installer/install.sh.in
+++ b/av/products/installer/install.sh.in
@@ -15,6 +15,7 @@ EXIT_FAIL_WDCTL_FAILED_TO_COPY=16
 EXIT_FAIL_WDCTL_FAILED_TO_START=17
 EXIT_FAIL_VERSIONEDCOPY=20
 EXIT_FAIL_INSTALL_PACKAGE=21
+EXIT_FAIL_COPY_MANIFEST=22
 
 STARTINGDIR=$(pwd)
 SCRIPTDIR=${0%/*}
@@ -60,75 +61,120 @@ then
         failure ${EXIT_FAIL_INSTALL_PACKAGE} "Unable to install setcap"
     fi
 fi
+PLUGIN_INSTALL="${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}"
+VAR="${PLUGIN_INSTALL}/var"
 
-#In case this is an upgrade request the watchdog stops the plugin
-#A failure with exit code 2 will be ignored as this just means the plugin was not registered
-#This could happen if a plugin is being freshly installed (e.g. for the first time)
-"${SOPHOS_INSTALL}/bin/wdctl" stop "${PLUGIN_NAME}" &>/dev/null || [ $? == 2 ] || echo Failed to stop plugin: ${PLUGIN_NAME}
+function install_product()
+{
+    #In case this is an upgrade request the watchdog stops the plugin
+    #A failure with exit code 2 will be ignored as this just means the plugin was not registered
+    #This could happen if a plugin is being freshly installed (e.g. for the first time)
+    "${SOPHOS_INSTALL}/bin/wdctl" stop "${PLUGIN_NAME}" &>/dev/null || [ $? == 2 ] || echo Failed to stop plugin: ${PLUGIN_NAME}
 
-#Create plugin registration file
-TEMP_REG_FILE=${SOPHOS_INSTALL}/tmp/${PLUGIN_NAME}.json
-sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/${PLUGIN_NAME}.json" >  "${TEMP_REG_FILE}"
-"${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_REG_FILE}"
-rm -f ${TEMP_REG_FILE}
+    #Create plugin registration file
+    local TEMP_REG_FILE=${SOPHOS_INSTALL}/tmp/${PLUGIN_NAME}.json
+    sed "s;SOPHOS_INSTALL_VALUE;${SOPHOS_INSTALL};g" "${DIST}/files/base/pluginRegistry/${PLUGIN_NAME}.json" >  "${TEMP_REG_FILE}"
+    "${SOPHOS_INSTALL}/bin/wdctl" copyPluginRegistration "${TEMP_REG_FILE}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_COPY} "Failed to copy registration ${TEMP_REG_FILE}"
+    rm -f ${TEMP_REG_FILE}
 
-#Install files
-for F in $(find $DIST/files/plugins -type f)
-do
-    $SOPHOS_INSTALL/base/bin/versionedcopy $F || failure ${EXIT_FAIL_VERSIONEDCOPY} "Failed to copy $F to installation"
-done
+    #Install files
+    find "$DIST/files/plugins" -type f -print0 \
+        | xargs -0 "$SOPHOS_INSTALL/base/bin/versionedcopy" || failure ${EXIT_FAIL_VERSIONEDCOPY} "Failed to copy files to installation"
 
-ln -s -f "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/sbin/uninstall.sh" "${SOPHOS_INSTALL}/base/update/var/installedproducts/${PRODUCT_LINE_ID}.sh"
+    ln -s -f "${PLUGIN_INSTALL}/sbin/uninstall.sh" "${SOPHOS_INSTALL}/base/update/var/installedproducts/${PRODUCT_LINE_ID}.sh"
 
-chmod 0711 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}"
-chmod 0711 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64"
-chmod 0755 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64"/*
-# Lock down libraries which are not needed by avscanner
-chmod 0700 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64/libpluginimpl.so"*
-chmod 0700 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64/libscanscheduler.so"*
-chmod 0700 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64/libsophosthreatdetectorimpl.so"*
-chmod 0700 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/lib64/libthreat_scanner.so"*
-chmod 0711 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/bin"
-chmod 0755 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/bin/avscanner"
-chmod -R 0710 "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/sbin"
+    chmod 0711 "${PLUGIN_INSTALL}"
+    chmod 0711 "${PLUGIN_INSTALL}/lib64"
+    chmod 0755 "${PLUGIN_INSTALL}/lib64"/*
+    # Lock down libraries which are not needed by avscanner
+    chmod 0700 "${PLUGIN_INSTALL}/lib64/libpluginimpl.so"*
+    chmod 0700 "${PLUGIN_INSTALL}/lib64/libscanscheduler.so"*
+    chmod 0700 "${PLUGIN_INSTALL}/lib64/libsophosthreatdetectorimpl.so"*
+    chmod 0700 "${PLUGIN_INSTALL}/lib64/libthreat_scanner.so"*
+    chmod 0711 "${PLUGIN_INSTALL}/bin"
+    chmod 0755 "${PLUGIN_INSTALL}/bin/avscanner"
+    chmod -R 0710 "${PLUGIN_INSTALL}/sbin"
 
-VAR="${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/var"
-mkdir -p "$VAR"
+    mkdir -p "$VAR"
 
-CHROOT="${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/chroot"
-CHROOT_LINK_DIR="${CHROOT}/${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}"
-mkdir -p ${CHROOT_LINK_DIR}
-ln -snf / ${CHROOT_LINK_DIR}/chroot
-mkdir -p ${CHROOT}/${SOPHOS_INSTALL}/base/etc/
-mkdir -p ${CHROOT}/${SOPHOS_INSTALL}/base/mcs/policy/
-mkdir -p ${CHROOT}/tmp
-chmod 0711 "$CHROOT"
+    CHROOT="${PLUGIN_INSTALL}/chroot"
+    CHROOT_LINK_DIR="${CHROOT}/${PLUGIN_INSTALL}"
+    mkdir -p ${CHROOT_LINK_DIR}
+    ln -snf / ${CHROOT_LINK_DIR}/chroot
+    mkdir -p ${CHROOT}/${SOPHOS_INSTALL}/base/etc/
+    mkdir -p ${CHROOT}/${SOPHOS_INSTALL}/base/mcs/policy/
+    mkdir -p ${CHROOT}/tmp
+    chmod 0711 "$CHROOT"
 
-## Create log directory symlinks for sophos_threat_detector
-mkdir -p "$CHROOT/log" "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/log" "${CHROOT_LINK_DIR}/log"
-ln -snf "$CHROOT/log" "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/log/sophos_threat_detector"
-ln -snf "/log" "${CHROOT_LINK_DIR}/log/sophos_threat_detector"
-ln -snf "sophos_threat_detector/sophos_threat_detector.log" "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/log/sophos_threat_detector.log"
+    ## Create log directory symlinks for sophos_threat_detector
+    mkdir -p "$CHROOT/log" "${PLUGIN_INSTALL}/log" "${CHROOT_LINK_DIR}/log"
+    ln -snf "$CHROOT/log" "${PLUGIN_INSTALL}/log/sophos_threat_detector"
+    ln -snf "/log" "${CHROOT_LINK_DIR}/log/sophos_threat_detector"
+    ln -snf "sophos_threat_detector/sophos_threat_detector.log" "${PLUGIN_INSTALL}/log/sophos_threat_detector.log"
 
-## Temporary - will need to adapt to hot-updating in SuSI
-cp ${SOPHOS_INSTALL}/base/lib64/libz.so.1 ${CHROOT}/susi/distribution_version/version1/
+    ## Temporary - will need to adapt to hot-updating in SuSI
+    cp ${SOPHOS_INSTALL}/base/lib64/libz.so.1 ${CHROOT}/susi/distribution_version/version1/
 
-# Enable DNS resolve on Ubuntu
-mkdir -p ${CHROOT}/etc ${CHROOT}/susi/distribution_version
+    # Enable DNS resolve on Ubuntu
+    mkdir -p ${CHROOT}/etc ${CHROOT}/susi/distribution_version
 
-chown -R ${USER_NAME}:${GROUP_NAME} "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}"
+    chown -R ${USER_NAME}:${GROUP_NAME} "${PLUGIN_INSTALL}"
 
 
-pushd "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/sbin" || failure ${EXIT_FAIL_CREATE_DIRECTORY} "Failed to find sbin directory"
-THREAT_DETECTOR="sophos_threat_detector_launcher"
-[[ -h "$THREAT_DETECTOR" ]] && THREAT_DETECTOR=$(readlink "$THREAT_DETECTOR")
-[[ -f "$THREAT_DETECTOR" ]] && setcap cap_sys_chroot=eip "$THREAT_DETECTOR"
-SCHEDULED_FILE_WALKER="scheduled_file_walker_launcher"
-[[ -h "$SCHEDULED_FILE_WALKER" ]] && SCHEDULED_FILE_WALKER=$(readlink "$SCHEDULED_FILE_WALKER")
-[[ -f "$SCHEDULED_FILE_WALKER" ]] && setcap cap_dac_read_search=eip "$SCHEDULED_FILE_WALKER"
-popd || failure ${EXIT_FAIL_CREATE_DIRECTORY} "Failed to return from sbin directory"
+    pushd "${PLUGIN_INSTALL}/sbin" || failure ${EXIT_FAIL_CREATE_DIRECTORY} "Failed to find sbin directory"
+    THREAT_DETECTOR="sophos_threat_detector_launcher"
+    [[ -h "$THREAT_DETECTOR" ]] && THREAT_DETECTOR=$(readlink "$THREAT_DETECTOR")
+    [[ -f "$THREAT_DETECTOR" ]] && setcap cap_sys_chroot=eip "$THREAT_DETECTOR"
+    SCHEDULED_FILE_WALKER="scheduled_file_walker_launcher"
+    [[ -h "$SCHEDULED_FILE_WALKER" ]] && SCHEDULED_FILE_WALKER=$(readlink "$SCHEDULED_FILE_WALKER")
+    [[ -f "$SCHEDULED_FILE_WALKER" ]] && setcap cap_dac_read_search=eip "$SCHEDULED_FILE_WALKER"
+    popd || failure ${EXIT_FAIL_CREATE_DIRECTORY} "Failed to return from sbin directory"
 
-ln -snf "${SOPHOS_INSTALL}/plugins/${PLUGIN_NAME}/bin/avscanner" /usr/local/bin/avscanner
+    ln -snf "${PLUGIN_INSTALL}/bin/avscanner" /usr/local/bin/avscanner
 
-#After install start the plugin
-"${SOPHOS_INSTALL}/bin/wdctl" start "${PLUGIN_NAME}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start plugin ${PLUGIN_NAME}"
+    #After install start the plugin
+    "${SOPHOS_INSTALL}/bin/wdctl" start "${PLUGIN_NAME}" || failure ${EXIT_FAIL_WDCTL_FAILED_TO_START} "Failed to start plugin ${PLUGIN_NAME}"
+
+    cp "$DIST/manifest.dat" "${VAR}/manifest.dat" || failure ${EXIT_FAIL_COPY_MANIFEST} "Failed to copy manifest from install-set to installation"
+}
+
+function update_supplement()
+{
+    # Copy supplement updates
+    find "$DIST/files/plugins/av/chroot/susi/distribution_version" -type f -print0 \
+        | xargs -0 "$SOPHOS_INSTALL/base/bin/versionedcopy" || failure ${EXIT_FAIL_VERSIONEDCOPY} "Failed to copy files to installation"
+
+    # reload sophos_threat_detector
+    local PID=$(ps -C sophos_threat_d -o pid= | awk '{print $1}')
+    if [[ -n "$PID" ]]
+    then
+        # This will terminate sophos_threat_detector until we have hot-reload functionality
+        kill -SIGUSR1 "$PID"
+    else
+        echo "sophos_threat_detector not running"
+    fi
+}
+
+function supplement_only_update()
+{
+    if [[ -f "${VAR}/manifest.dat" ]]
+    then
+        cmp "$DIST/manifest.dat" "${VAR}/manifest.dat"
+    else
+        return 1
+    fi
+}
+
+if supplement_only_update
+then
+    # no changes in product
+    # supplement only update
+    # if sophos_threat_detector is running, then send it a signal
+    update_supplement
+else
+    install_product
+fi
+
+<<<<<<< HEAD
+=======
+>>>>>>> [LINUXDAR-1788] Alter install script to assume supplement update only if manifest file hasn't changed.
