[av] [LINUXDAR-3855] Remove the downgrade if statement

diff --git a/av/products/installer/uninstall.sh.in b/av/products/installer/uninstall.sh.in
--- a/av/products/installer/uninstall.sh.in
+++ b/av/products/installer/uninstall.sh.in
@@ -101,8 +101,5 @@ function removeUser()
   return 0
 }
 
-if (( DOWNGRADE == 0 ))
-then
-  removeUser    sophos-spl-av || echo "Failed to delete user: sophos-spl-av"
-  removeUser    sophos-spl-threat-detector || echo "Failed to delete user: sophos-spl-threat-detector"
-fi
+removeUser    sophos-spl-av || echo "Failed to delete user: sophos-spl-av"
+removeUser    sophos-spl-threat-detector || echo "Failed to delete user: sophos-spl-threat-detector"
